### ISSUE TITLE
Make sub-task example more HAPI

### ISSUE THREAD

**Issue by rlander-adaptavist** [void-dot-admin/void-script-runner#1]
Hey Andrei, 

I took a look over your code, here is a suggestion to make it more HAPI:

```
import com.atlassian.jira.component.ComponentAccessor

def parentIssue = issue

if (parentIssue.isSubTask()) {
    return
}

def subTask = parentIssue.createSubTask('Sub-task') {
    setSummary("Sub-task for: ${parentIssue.summary}")
    setDescription(parentIssue.description)
    setPriority(parentIssue.priority)

    def taskChoice = parentIssue.getCustomFieldValue('Task choice')

    if (taskChoice) {
        setCustomFieldValue('Task choice', taskChoice)
    }

    setAssignee {
        if (parentIssue.assignee) {
            set(parentIssue.assignee)
        } else {
            automatic()
        }
    }

    setComponents {
        parentIssue.components.each { add(it) }
    }

}

def attachmentManager = ComponentAccessor.getAttachmentManager()
attachmentManager.copyAttachments(parentIssue, Users.loggedInUser, subTask.key)
```

HAPI doesn't currently have a mechanism for copying attachments directly, we'll be working on that shortly.

Keen to hear your thoughts :)

**Comment by void-dot-admin** [comment]
Wow, so happy to see that you even had a look on my templates <3 thank you so much.

Your code looks amazing,  is better written and is more cleaner. I've created a pull request with your code and added it to the repo so people can use the cleaner version from you.

You made my day man :D I know that this issue was opened like months ago but due to life I didn't had time to even look on what is happening here and I just saw it months later :(

Thanks again for this and thanks for contributing to this repo, I'm amazed :))))
